timer: 120
#发消息的间隔，单位为秒
Order:
  - '1a'
  - '1b'
  - '1c'
  - '1b'
  - '1d'
  - '1e'
  - '1b'
#消息的顺序，插件将根据间隔从上往下播报
Messages:
  1a:
    - " "
    - "§3Mhxj§bClub §f▶"
    - "§7◈ &bLKQ2&f-&3Kisatsutai &f已封禁 §c{LITEBANS_BANCOUNT} §f名玩家"
    - "§7◈ §f请珍惜游戏账号, 拒绝作弊, 谨防受骗上当."
    - " "
  1b:
    - ' '
    - '§3Mhxj§bClub §f▶'
    - '&7◈ &f在b站、快手、抖音等视频平台发布关于服务器的视频，就可以获得点券！'
    - '&7◈ &f粉丝量到达一定要求或者视频播放量达标可以获得主播称号！ 福利多多!'
    - ' '
  1c:
    - ' '
    - '§3Mhxj§bClub §f▶'
    - '&7◈ &f服务器每个月都需要400r的运行费用 各位如果有能力，还请帮我们回点血'
    - '&7◈ &f赞助地址&c http://top.fanet.top &f听我说谢谢你'
    - ' '
  1d:
    - ' '
    - '§3Mhxj§bClub §f▶'
    - '&7◈ &f觉得服务器好玩就拉上自己的好友一起来玩吧！'
    - '&7◈ &f人多才热闹 才好玩嘛'
    - ' '
  1e:
    - ' '
    - '§3Mhxj§bClub §f▶'
    - '&7◈ &f如果你对服务器有任何的意见， 欢迎联系我们'
    - '&7◈ &fQQ群: &e169775061 &fFrk: &e1605532208 &fwhohh: &e1951723651'
    - ' '
    #如果需要添加网页链接 请尽量在网址两边空格 以免程序识别错误
#配置消息:
# 消息名:
#   - '内容 第一行'
#   - '内容 第二行'
#编辑完后记得在order中添加顺序，否则不会启用